- .gitignore
- .gitmodules
- Makefile
- rbm
- rbm.conf
- tools/clean-old
This PR eliminates most of the diff between ncdns-repro and upstream tor-browser-build.  It wasn't feasible to properly audit most of the diff, and upstream has substantially better QA resources than we do.  If any parts of the diff were actually required for ncdns, I suggest either submitting them as follow-up PR's here (with comments explaining why they're needed), or else submitting them upstream to Tor.
I can confirm that `make release-linux-x86_64` produces a working binary (modulo cgo issues that I'll file separately) with this PR applied.  I haven't tried any of the other targets.
> Shrink diff against upstream Tor as much as possible

- keyring/binutils.gpg
- projects/binutils
- projects/gcc
- projects/github.com,coreos,go-systemd/config
- projects/github.com,hlandau,buildinfo/config
- projects/github.com,hlandau,dexlogconfig/config
- projects/gopkg.in,hlandau,madns.v1/config
- projects/gopkg.in,hlandau,service.v2/config
- projects/gopkg.in,hlandau,svcutils.v1/config
- projects/ncdns/build
- projects/ncdns/config
This should improve reproducibility, and it might also fix whatever bugs might be caused by the ancient Wheezy binutils/gcc.
> Use Tor's binutils/gcc (not Wheezy's) for Go projects that use cgo

- hashlist
- projects/github.com,btcsuite,winsvc/config
- projects/github.com,hlandau,dexlogconfig/config
- projects/golang.org,x,sys
- projects/gopkg.in,hlandau,service.v2/config
- projects/mingw-w64
- projects/ncdns/config
This PR fixes the build errors for the `release-windows-x86_64` target.  I haven't yet tested the `release-windows-i686` target, but it's likely to benefit from these fixes too.
> Fix windows builds

- projects/dnssec-hsts-native/build
- projects/dnssec-hsts-native/config
- projects/dnssec-hsts/build
- projects/dnssec-hsts/config
- projects/github.com,namecoin,qlib/config
This PR adds DNSSEC-HSTS (both the WebExtensions and native components).  It also adds qlib since it's a dependency of DNSSEC-HSTS.  qexe is considered out of scope for this PR.
Fixes https://github.com/namecoin/ncdns-repro/issues/14
> Add DNSSEC-HSTS

- projects/certdehydrate-dane-rest-api/build
- projects/certdehydrate-dane-rest-api/config
- projects/dnssec-hsts-native/config
- projects/github.com,miekg,dns/config
- projects/github.com,namecoin,crosssign/config
- projects/github.com,namecoin,qlib/config
- projects/github.com,namecoin,safetlsa/config
- projects/ncdns/build
- projects/ncdns/config
Fixes https://github.com/namecoin/ncdns-repro/issues/11 .  Fixes https://github.com/namecoin/ncdns-repro/issues/13 .  Fixes https://github.com/namecoin/ncdns-repro/issues/17 .
Only tested on GNU/Linux x86_64 target.  Other targets are likely to work fine.
TODO:
> Add certdehydrate-dane-rest-api and its dependencies

- hashlist
- projects/github.com,miekg,pkcs11/config
- projects/github.com,namecoin,pkcs11mod/config
- projects/ncp11/build
- projects/ncp11/config
Fixes https://github.com/namecoin/ncdns-repro/issues/10 .  Fixes https://github.com/namecoin/ncdns-repro/issues/16 .
~~Only tested on GNU/Linux targets.  Windows definitely won't work yet due to an ncp11/pkcs11mod bug that's out of scope for this PR.~~  GNU/Linux and Windows now both work.  macOS is untested.
TODO:
> Add ncp11 project and its dependencies

- projects/dnssec-hsts-native/build
- projects/dnssec-hsts-native/config
The JSON manifest file is needed in order to use dnssec-hsts-native with Firefox; not sure why I forgot to add it here originally.
> dnssec-hsts-native: Add JSON manifest to output

- Makefile
This is a temporary kludge until we port over Tor's `release` project.
> Makefile: also build the non-ncdns projects

- projects/github.com,namecoin,x509-signature-splice/config
- projects/ncdns/build
- projects/ncdns/config
This PR bumps the version of ncdns to add support for name-constrained CA's in `generate_nmc_cert`.
> Bump ncdns version (use-ca in generate_nmc_cert)

- projects/certdehydrate-dane-rest-api/config
- projects/dnssec-hsts-native/config
- projects/dnssec-hsts/config
- projects/github.com,namecoin,crosssign/config
- projects/github.com,namecoin,crosssignnameconstraint/config
- projects/github.com,namecoin,pkcs11mod/config
- projects/github.com,namecoin,qlib/config
- projects/github.com,namecoin,safetlsa/config
- projects/github.com,namecoin,tlsrestrictnss/config
- projects/ncdns/config
- projects/ncp11/config
- projects/ncprop279/config
This is expected to be the last PR prior to the ncdns-repro v0.0.9 tag.
> Set project versions for ncdns 0.0.9

- projects/github.com,namecoin,x509-signature-splice/config
Previously, tor-browser-build and ncdns-repro needed to be synchronized carefully, because tor-browser-build commits to a Go version, while ncdns-repro commits to an x509-signature-splice version.  This patch allows the x509-signature-splice project work with arbitrary Go versions without modifying the ncdns-repro repo, thereby eliminating the need for careful synchronization of tor-browser-build and ncdns-repro.
> x509-signature-splice: Support multiple Go versions

- keyring/clang.gpg
- projects/clang
- projects/github.com,miekg,dns/config
- projects/golang.org,x,crypto
- projects/golang.org,x,crypto,ed25519/config
- projects/golang.org,x,net,ip/config
- projects/golang.org,x,sys,unix/config
This PR fixes various build errors affecting miekg/dns v1.1.16 (introduced by the upstream dependency bump in https://github.com/namecoin/ncdns-repro/pull/54 ).
> Fix miekg/dns v1.1.16

- projects/ncdns/build
- projects/ncdns/config
- projects/ncprop279/build
- projects/ncprop279/config
This PR exposes https://github.com/namecoin/ncdns/pull/115 as an rbm target.
TODO:
> ncdns: Support disabling TLSA

- Makefile
- setup-submodule-symlinks
> Use parent tor-browser-build instead of submodule if available

- projects/certdehydrate-dane-rest-api/build
- projects/dnssec-hsts-native/build
- projects/ncdns/build
- projects/ncp11/build
- projects/ncprop279/build
This improves build reproducibility.
Fixes https://github.com/namecoin/ncdns-repro/issues/57
> Set static build ID in Go linker flags

- .cirrus.yml
- Makefile
- projects/clang-source
- projects/gosplicesign/config
- projects/libtapi
- projects/ncdns/config
- projects/ninja
- projects/plain-binaries/build
- projects/plain-binaries/config
- projects/release/build
- projects/release/config
- rbm.conf
- rbm.local.conf.example
- tools/checkpoints.patch
- tools/cirrus_build_project.sh
- tools/cirrus_gen_yml.sh
- tools/cirrus_pack_interrupted.sh
- tools/cirrus_unpack_interrupted.sh
- tools/container-interrupt.sh
- tools/container-pids.sh
- tools/patch-tor-to-namecoin.sh
- tools/rbm.local.conf.onetarget
This PR enables building our rbm projects on Cirrus CI.  This code is intended to be submitted upstream to Tor Browser in the future, but for now Namecoin will incubate it until I'm convinced it's stable.
> Add Cirrus rbm builds

- tools/cirrus_build_project.sh
Don't just do a dry-run.  Should fix the cache overflow that was affecting https://github.com/namecoin/ncdns-repro/pull/89#issuecomment-804303491 .
> Cirrus: Actually clean old output files

- tools/cirrus_build_project.sh
Fixes https://github.com/namecoin/ncdns-repro/issues/98
> Cirrus: Only run ./tools/clean-old on download task

- .cirrus.yml
- tools/cirrus_build_project.sh
- tools/cirrus_gen_yml.sh
Should improve the odds of the output caches being unmodified, which will save us some upload time.
> Cirrus: Segregate plain-binaries cache

- .cirrus.yml
- tools/cirrus_gen_yml.sh
PR's from non-contributors don't have access to our Cirrus signing keys; trying to sign anyway causes the task to error.
> Cirrus: Don't sign binaries from PR's

- tools/namecoin-bump-versions.sh
Upstream ISC no longer supports Windows as of BIND 9.17 branch.
> Tools: Blacklist BIND 9.17+ for Windows

- tools/namecoin-bump-versions.sh
This fixes a fail where latest `v0.2.2` and current `v0.2` were detected as equal.
> tools: Fix substring matching in bump script

- projects/ncdns/build
- projects/ncdns/config
Package is deprecated and was factored out into its own repo.
> ncdns: Remove tlsrestrictchromium

- projects/ncdns-nsis/build
- projects/ncdns-nsis/config
We now chainload Electrum-NMC setup from ncdns-nsis.  Also avoid hardcoded PE version constant.
> ncdns-nsis: Add Electrum-NMC dependency

- tools/namecoin-bump-versions.sh
Latest releases don't build in rbm, and I don't have time to fix this right now.
> Bump: Temporarily disable Electrum-NMC project

- .cirrus.yml
- tools/cirrus_build_project.sh
- tools/cirrus_gen_yml.sh
Should decrease risk of race conditions when we have multiple builds happening at once.
> Isolate intermediate Cirrus caches by PR number

- .cirrus.yml
- tools/cirrus_gen_yml.sh
This was unintentionally enabled and was probably impeding performance.
> Disable statefulness of Cirrus
