projects/ncdns/build

Refs https://github.com/namecoin/ncdns-repro/issues/2#issuecomment-488030654

ncdns: Fix linux/386 builds

---

keyring/cmake.gpg
keyring/llvm.gpg
projects/cctools
projects/cmake
projects/gopkg.in,hlandau,service.v2/config
projects/gopkg.in,hlandau,svcutils.v1/config
projects/llvm
projects/macosx-toolchain
projects/ncdns/build
projects/ncdns/config

This PR fixes the build errors for the `release-osx-x86_64` target.

Fix macOS builds

---

projects/electrum-nmc/build
projects/electrum-nmc/config

Fixes https://github.com/namecoin/ncdns-repro/issues/30

Add electrum-nmc project

---

projects/github.com,namecoin,crosssignnameconstraint/config
projects/github.com,namecoin,tlsrestrictnss/config
projects/ncdns/config
projects/ncprop279/build
projects/ncprop279/config

Fixes https://github.com/namecoin/ncdns-repro/issues/5
Fixes https://github.com/namecoin/ncdns-repro/issues/7
Fixes https://github.com/namecoin/ncdns-repro/issues/9
Fixes https://github.com/namecoin/ncdns-repro/issues/35

Add ncprop279 project

---

projects/ncp11/config

Fixes ncp11 build failures on linux and osx targets.

Bump ncp11 version

---

projects/certdehydrate-dane-rest-api/config
projects/dnssec-hsts-native/config
projects/github.com,miekg,dns/config
projects/github.com,namecoin,qlib/config

Remove var/dns_q_compat hack since qlib v0.0.2 fixes that issue.

Bump qlib to v0.0.2

---

projects/github.com,mattn,go-isatty/config

This dependency was added upstream.

Add goxsys dependency to mattn/go-isatty

---

.travis.yml
.travis/check-project-tags
.travis/check-tbb-tags
Makefile
projects/godns/config
projects/goservice/config
projects/gounits/config
rbm.conf

Also add Travis check for dependency version updates.

Bump dependencies to latest as of 2019 09 29

---

projects/goxnetip/config

Fixes https://github.com/namecoin/ncdns-repro/issues/64

goxnetip: Add goxsysunix dependency for macOS/Linux

---

.cirrus.yml
tools/cirrus_gen_yml.sh

Fixes https://github.com/namecoin/ncdns-repro/issues/93

Cirrus: Enable timestamp logging

---

tools/cirrus_build_project.sh

Fixes https://github.com/namecoin/ncdns-repro/issues/94

Cirrus: Verify Cirrus YML determinism

---

.cirrus.yml
tools/cirrus_build_project.sh
tools/cirrus_gen_yml.sh
tools/cirrus_pack_git.sh
tools/cirrus_unpack_git.sh

Fixes https://github.com/namecoin/ncdns-repro/issues/100

Cirrus: Segregate Git indexes from other Git data

---

tools/cirrus_build_project.sh

Fixes https://github.com/namecoin/ncdns-repro/issues/106

Cirrus: Skip showconf on download task

---

tools/namecoin-bump-versions.sh

This makes it more straightforward to cherry-pick parts of the generated PR's.

Cirrus: Bump one project per commit

---

projects/gointernal/config
projects/gopretty/config

Adds dependency on `gointernal`.

Bump gopretty to v0.3.0

---

tools/namecoin-bump-versions.sh

Should make it easier to debug when an update isn't detected.

tools: Increase verbosity of bump script

---

LICENSE
README.md

Fixes https://github.com/namecoin/ncdns-repro/issues/135

Relicense under tor-browser-build license

---

.cirrus.yml
projects/plain-binaries/build
projects/plain-binaries/config
tools/cirrus_gen_yml.sh

Refs https://github.com/namecoin/ncdns-repro/issues/155

Disable ncp11 on macOS

---

projects/electrum-nmc/config
projects/generate_nmc_cert/config
projects/godns/config
projects/goisatty/config
projects/gotoml/config
projects/ncdns-nsis/config
projects/ncdns/config

Bump dependencies

---

tools/cirrus_build_project.sh
tools/namecoin-bump-versions.sh

Also fix missing `jq` dependency.

Bump script: include versions in generated commit messages

---

tools/cirrus_build_project.sh

Makes it easier to debug cache preservation bugs and cache splitting.

Log output cache contents

---

projects/gotlsrestrictnss/config
projects/ncprop279/config

ncprop279 / gotlsrestrictnss: Replace Git SHA1 with GPG sig
